USE xworkz;
ALTER TABLE student ADD COLUMN (cgpa int,percentage int,marks_obt int,total_marks int,height int,weight int,pet_name varchar(20),school varchar(30),clg_name varchar(40),profile varchar(50));
DESC student;
ALTER TABLE phone ADD COLUMN (pass_code int,imei int,cost int,color varchar(10),replacement int,emi int,cod varchar(10),sim_type varchar(30),net_type varchar(40),zoom varchar(10));
ALTER TABLE cricket ADD COLUMN (extra_batter int,extra_bowler int,bench int,debue int,bowl_speed int,prize int,sponsor varchar(20),b_ambassador varchar(30),head varchar(40),goat varchar(50));
ALTER TABLE laptop ADD COLUMN (core int,display int,color varchar(10),os varchar(10),battery_backup int,weight int,model_name varchar(20),graphics varchar(30),resolution varchar(40),office varchar(50));
ALTER TABLE comoany ADD COLUMN (area int,tie_up int,m_turnover int,annual_turnover int,no_employess int,started date,services varchar(20),clients varchar(50),ceo varchar(40),founder varchar(50));
ALTER TABLE food ADD COLUMN (ingredients int,minutes int,chief varchar(20),oil int,fibre int,carbohydrates int,street_food varchar(20),fast_food varchar(30),healthy int,quantity int);
ALTER TABLE ipl ADD COLUMN (runs int,to_defend int,to_win int,to_chase int,won_by int,lost_by int,final_team1 varchar(20),final_team2 varchar(30),captain_name1 varchar(40),captain_name2 varchar(50));
ALTER TABLE building ADD COLUMN (expenditure int,helipad int,days int,material int,labour int,rent int,b_owner varchar(20),builder varchar(30),contractor varchar(40),profile varchar(50));
ALTER TABLE transport ADD COLUMN (t_types2 int,t_names2 varchar(20),t_way2 varchar(20),high_speed int,low_speed varchar(20),environment_friendly2 varchar(20),most_used2 varchar(20),low_pollutant varchar(20),high_pollutant varchar(20),cheapest varchar(20));
ALTER TABLE course ADD COLUMN (c_name2 varchar(20),institute2 varchar(30),c2_fees int,c2_field varchar(20),c2_duration int,c2_start_date date,c2_end_date date,c2_students int,c2_scope varchar(20),c2_drives int);

ALTER TABLE student RENAME COLUMN id TO id_no;
ALTER TABLE student RENAME COLUMN address TO permanant_address;
ALTER TABLE phone RENAME COLUMN pass_code TO password;
ALTER TABLE phone RENAME COLUMN imei TO imei_no;
ALTER TABLE cricket RENAME COLUMN goat TO goat_name;
ALTER TABLE cricket RENAME COLUMN b_ambassador TO ambassador;
ALTER TABLE laptop RENAME COLUMN os TO os_name;
ALTER TABLE laptop RENAME COLUMN office TO ms_office;
ALTER TABLE comoany RENAME COLUMN area TO acres;
ALTER TABLE comoany RENAME COLUMN no_employess TO no_employees;
ALTER TABLE food RENAME COLUMN minutes TO time;
ALTER TABLE food RENAME COLUMN street_food TO street_food_name;
ALTER TABLE ipl RENAME COLUMN final_team1 TO final_team_1;
ALTER TABLE ipl RENAME COLUMN final_team2 TO final_team_2;
ALTER TABLE building RENAME COLUMN expenditure TO expenses;
ALTER TABLE building RENAME COLUMN labour TO labourers;
ALTER TABLE transport RENAME COLUMN t_types2 TO t_types_2;
ALTER TABLE transport RENAME COLUMN t_names2 TO t_names_2;
ALTER TABLE course RENAME COLUMN c_name2 TO c_name_2;
ALTER TABLE course RENAME COLUMN institute2 TO institute_2;

ALTER TABLE student MODIFY COLUMN id_no VARCHAR(20);
ALTER TABLE student MODIFY COLUMN permanant_address VARCHAR(50);
ALTER TABLE phone MODIFY COLUMN password VARCHAR(10);
ALTER TABLE phone MODIFY COLUMN imei_no VARCHAR(20);
ALTER TABLE cricket MODIFY COLUMN goat_name VARCHAR(30);
ALTER TABLE cricket MODIFY COLUMN ambassador VARCHAR(50);
ALTER TABLE laptop MODIFY COLUMN os_name VARCHAR(20);
ALTER TABLE laptop MODIFY COLUMN ms_office VARCHAR(30);
ALTER TABLE comoany MODIFY COLUMN acres BIGINT;
ALTER TABLE comoany MODIFY COLUMN no_employees BIGINT;
ALTER TABLE food MODIFY COLUMN time TIME;
ALTER TABLE food MODIFY COLUMN street_food_name VARCHAR(50);
ALTER TABLE ipl MODIFY COLUMN final_team_1 VARCHAR(50);
ALTER TABLE ipl MODIFY COLUMN final_team_2 VARCHAR(50);
ALTER TABLE building MODIFY COLUMN expenses BIGINT;
ALTER TABLE building MODIFY COLUMN labourers BIGINT;
ALTER TABLE transport MODIFY COLUMN t_types_2 BIGINT;
ALTER TABLE transport MODIFY COLUMN t_names_2 VARCHAR(50);
ALTER TABLE course MODIFY COLUMN c_name_2 VARCHAR(50);
ALTER TABLE course MODIFY COLUMN institute_2 VARCHAR(50);

ALTER TABLE student DROP COLUMN height;
ALTER TABLE student DROP COLUMN weight;
ALTER TABLE phone DROP COLUMN zoom;
ALTER TABLE phone DROP COLUMN net_type;
ALTER TABLE cricket DROP COLUMN goat_name;
ALTER TABLE cricket DROP COLUMN ambassador;
ALTER TABLE laptop DROP COLUMN core;
ALTER TABLE laptop DROP COLUMN ms_office;
ALTER TABLE comoany DROP COLUMN tie_up;
ALTER TABLE comoany DROP COLUMN no_employees;
ALTER TABLE food DROP COLUMN time;
ALTER TABLE food DROP COLUMN carbohydrates;
ALTER TABLE ipl DROP COLUMN final_team_1;
ALTER TABLE ipl DROP COLUMN final_team_2;
ALTER TABLE building DROP COLUMN helipad;
ALTER TABLE building DROP COLUMN profile;
ALTER TABLE transport DROP COLUMN t_types_2;
ALTER TABLE transport DROP COLUMN t_names_2;
ALTER TABLE course DROP COLUMN c_name_2;
ALTER TABLE course DROP COLUMN institute_2;
